### ISSUE TITLE
it should output DOIs in full upper case

### ISSUE THREAD

**Issue by egonw** [citation-js/plugin-quickstatements#4]

**Comment by larsgw** [comment]
A fix would be somewhere in this `switch` statement, with a `case` for `"DOI"` where the value is returned in upper case:

https://github.com/citation-js/plugin-quickstatements/blob/e6a30e4a1e03d9edbcc4d985d8107f577a4450ab/src/output.js#L81-L82

**Comment by larsgw** [comment]
Published in [`0.3.4`](https://www.npmjs.com/package/@citation-js/plugin-quickstatements/v/0.3.4) (with a fix to quote the DOI and updated tests)
